// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xscyhnstvjyofxglvxat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY3lobnN0dmp5b2Z4Z2x2eGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjYzNTYsImV4cCI6MjA2NzkwMjM1Nn0.4J7KCWnuFyk71FVW147SCvc-J7ZQycTlEnBlXd_8zM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});